
// Philosophical quotes about the brevity of life in multiple languages

import { Language } from './translations';

type QuoteCollection = {
  [key in Language]: string[];
};

export const lifeQuotes: QuoteCollection = {
  // English quotes
  en: [
    "Life is short, art is long. — Hippocrates",
    "Time is the most valuable thing a man can spend. — Theophrastus",
    "The wise man does not sit to lament, but rejoices that he has lived. — William Shakespeare",
    "Our fear of death is like our fear of ocean: it's in its vastness, not in its waves. — Rabindranath Tagore",
    "Fate shuffles the cards, and we play. — Arthur Schopenhauer",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. — Albert Einstein",
    "Life is brief, but if you know how to use it, it will be long enough. — Seneca",
    "It's not time that changes things, but what we make of it. — Thoreau",
    "Only a life lived for others is worth living. — Albert Einstein",
    "Life is what happens while you're busy making other plans. — John Lennon",
    "The essence of life is to move forward; whoever has stopped, has already died. — Machado de Assis",
    "Life is a constant flow; nothing remains the same. — Heraclitus",
    "Every man dies. Not every man really lives. — William Wallace",
    "Life is like an echo: if you don't like what you see, change what you do. — Jim Rohn",
    "The greatest glory in living is not in never falling, but in rising every time we fall. — Nelson Mandela",
    "The unexamined life is not worth living. — Socrates",
    "Life is like a camera: focus on what's important, capture good moments, develop negatives into positives. — Unknown",
    "Time is a child playing dice: the kingdom of a child. — Heraclitus",
    "Life without reflection is not worth living. — Socrates",
    "Don't count the days, make the days count. — Muhammad Ali",
    "Life is really simple, but we insist on making it complicated. — Confucius",
    "The greatest discovery of my generation is that human beings can alter their lives by altering their attitudes of mind. — William James",
    "Happiness is not in living, but in knowing how to live. — Fyodor Dostoevsky",
    "Life is an eternal new beginning. — Jean-Paul Sartre",
    "Life is too short to be little. — Benjamin Disraeli",
    "Life is either a daring adventure or nothing. — Helen Keller",
    "True wisdom consists in knowing one's own ignorance. — Socrates",
    "The secret of human existence is not only to live but to have something to live for. — Fyodor Dostoevsky",
    "Man cannot discover new oceans unless he has the courage to lose sight of the shore. — André Gide",
    "Before judging my life or my character, walk in my shoes and travel the path I have traveled. — Atticus",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. — Mahatma Gandhi",
    "The man who moves mountains begins by carrying away small stones. — Chinese Proverb",
    "It is during storms that we discover the courage of sailors. — Thomas Fuller",
    "I hate how people romanticize suffering instead of valuing each moment. — Marina Keegan",
    "You cannot step into the same river twice, for fresh waters are always flowing. — Heraclitus",
    "Nothing is permanent except change. — Heraclitus",
    "Life is what we make of it. Travels are travelers. What we see is not what we see but what we are. — Fernando Pessoa",
    "We should not be afraid of death, but of never having begun to live. — Marcus Aurelius",
    "The man who thinks he knows something, knows nothing. The man who knows he knows nothing, knows everything. — Socrates",
    "Everyone thinks of changing the world, but no one thinks of changing himself. — Leo Tolstoy",
    "We are what we repeatedly do. Excellence, therefore, is not an act but a habit. — Aristotle",
    "The mind that opens to a new idea never returns to its original size. — Albert Einstein",
    "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did. — Mark Twain",
    "Be the change you wish to see in the world. — Mahatma Gandhi",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "All that we are is the result of what we have thought. — Buddha",
    "The only way to do great work is to love what you do. — Steve Jobs",
    "The hardest thing is not to accept that everything ends, but to understand that sometimes everything ends before it even begins. — José Saramago",
    "For every minute you are angry, you lose sixty seconds of happiness. — Ralph Waldo Emerson"
  ],

  // Portuguese quotes
  pt: [
    "A vida é breve, a arte é longa. — Hipócrates",
    "O tempo é a coisa mais valiosa que um homem pode gastar. — Teofrasto",
    "O sábio não se senta para lamentar, mas se alegra por ter vivido. — William Shakespeare",
    "Nosso medo da morte é como nosso medo do oceano: está em sua vastidão, não em suas ondas. — Rabindranath Tagore",
    "O destino embaralha as cartas, e nós jogamos. — Arthur Schopenhauer",
    "A vida é como andar de bicicleta. Para manter o equilíbrio, você deve continuar se movendo. — Albert Einstein",
    "A vida é breve, mas se você souber usá-la, ela será longa o suficiente. — Sêneca",
    "Não é o tempo que muda as coisas, mas o que fazemos dele. — Thoreau",
    "Somente uma vida vivida para os outros vale a pena ser vivida. — Albert Einstein",
    "A vida é aquilo que acontece enquanto você está ocupado fazendo outros planos. — John Lennon",
    "A essência da vida é ir para frente; quem ficou parado, já morreu. — Machado de Assis",
    "A vida é um constante fluir; nada permanece o mesmo. — Heráclito",
    "Todo homem morre. Nem todo homem vive de verdade. — William Wallace",
    "A vida é como um eco: se não gosta do que vê, mude o que faz. — Jim Rohn",
    "A maior glória na vida não é nunca cair, mas levantar-se a cada vez que caímos. — Nelson Mandela",
    "A vida não examinada não vale a pena ser vivida. — Sócrates",
    "A vida é como uma câmera: foque no que é importante, capture bons momentos, desenvolva negativos em positivos. — Desconhecido",
    "O tempo é uma criança jogando dados: reino de criança. — Heráclito",
    "A vida sem reflexão não vale a pena ser vivida. — Sócrates",
    "Não conte os dias, faça os dias contarem. — Muhammad Ali",
    "A vida é realmente simples, mas insistimos em torná-la complicada. — Confúcio",
    "A maior descoberta da minha geração é que os seres humanos podem alterar suas vidas alterando suas atitudes mentais. — William James",
    "A felicidade não está em viver, mas em saber viver. — Fiódor Dostoiévski",
    "A vida é um eterno recomeço. — Jean-Paul Sartre",
    "A vida é curta para ser pequena. — Benjamin Disraeli",
    "A vida é uma aventura ousada ou não é nada. — Helen Keller",
    "A verdadeira sabedoria está em reconhecer a própria ignorância. — Sócrates",
    "O segredo da existência humana está não só em viver, mas também em saber para que se vive. — Fiódor Dostoiévski",
    "O homem não pode descobrir novos oceanos a menos que tenha coragem de perder de vista a costa. — André Gide",
    "Antes de julgar minha vida ou meu caráter, calce os meus sapatos e percorra o caminho que eu percorri. — Atticus",
    "Viva como se fosse morrer amanhã. Aprenda como se fosse viver para sempre. — Mahatma Gandhi",
    "O homem que remove montanhas começa carregando pequenas pedras. — Provérbio chinês",
    "É durante as tempestades que descobrimos a coragem dos navegantes. — Thomas Fuller",
    "Odeio como as pessoas romantizam o sofrimento em vez de valorizar cada momento. — Marina Keegan",
    "Não se pode entrar duas vezes no mesmo rio, pois novas águas estão sempre fluindo. — Heráclito",
    "Nada é permanente, exceto a mudança. — Heráclito",
    "A vida é o que fazemos dela. As viagens são os viajantes. O que vemos não é o que vemos, mas o que somos. — Fernando Pessoa",
    "Não devemos ter medo da morte, mas sim de nunca termos começado a viver. — Marcus Aurelius",
    "O homem que acha que sabe algo, não sabe nada. O homem que sabe que não sabe, sabe tudo. — Sócrates",
    "Todo mundo pensa em mudar o mundo, mas ninguém pensa em mudar a si mesmo. — Leon Tolstoy",
    "Somos o que repetidamente fazemos. A excelência, portanto, não é um ato, mas um hábito. — Aristóteles",
    "A mente que se abre a uma nova ideia jamais voltará ao seu tamanho original. — Albert Einstein",
    "Daqui a vinte anos, você estará mais desapontado pelas coisas que não fez do que pelas que fez. — Mark Twain",
    "Seja a mudança que você quer ver no mundo. — Mahatma Gandhi",
    "Não importa o quão devagar você vá, desde que você não pare. — Confúcio",
    "Tudo o que somos é resultado do que pensamos. — Buda",
    "A única maneira de fazer um excelente trabalho é amar o que você faz. — Steve Jobs",
    "O mais difícil não é aceitar que tudo termina, mas compreender que, às vezes, tudo termina antes mesmo de começar. — José Saramago",
    "Para cada minuto que você está com raiva, perde sessenta segundos de felicidade. — Ralph Waldo Emerson"
  ],

  // Spanish quotes
  es: [
    "La vida es breve, el arte es largo. — Hipócrates",
    "El tiempo es lo más valioso que una persona puede gastar. — Teofrasto",
    "El sabio no se sienta a lamentarse, sino que se alegra de haber vivido. — William Shakespeare",
    "Nuestro miedo a la muerte es como nuestro miedo al océano: está en su inmensidad, no en sus olas. — Rabindranath Tagore",
    "El destino baraja las cartas, y nosotros jugamos. — Arthur Schopenhauer",
    "La vida es como montar en bicicleta. Para mantener el equilibrio, debes seguir moviéndote. — Albert Einstein",
    "La vida es breve, pero si sabes cómo usarla, será lo suficientemente larga. — Séneca",
    "No es el tiempo lo que cambia las cosas, sino lo que hacemos con él. — Thoreau",
    "Solo una vida vivida para los demás merece la pena ser vivida. — Albert Einstein",
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes. — John Lennon",
    "La esencia de la vida es avanzar; quien se ha detenido, ya ha muerto. — Machado de Assis",
    "La vida es un flujo constante; nada permanece igual. — Heráclito",
    "Todo hombre muere. No todo hombre realmente vive. — William Wallace",
    "La vida es como un eco: si no te gusta lo que ves, cambia lo que haces. — Jim Rohn",
    "La mayor gloria en la vida no está en no caer nunca, sino en levantarnos cada vez que caemos. — Nelson Mandela",
    "Una vida sin examen no merece la pena ser vivida. — Sócrates",
    "La vida es como una cámara: enfócate en lo importante, captura buenos momentos, convierte los negativos en positivos. — Desconocido",
    "El tiempo es un niño jugando a los dados: reino de un niño. — Heráclito",
    "La vida sin reflexión no vale la pena vivirla. — Sócrates",
    "No cuentes los días, haz que los días cuenten. — Muhammad Ali",
    "La vida es realmente simple, pero insistimos en hacerla complicada. — Confucio",
    "El mayor descubrimiento de mi generación es que los seres humanos pueden cambiar sus vidas cambiando sus actitudes mentales. — William James",
    "La felicidad no está en vivir, sino en saber vivir. — Fiódor Dostoyevski",
    "La vida es un eterno nuevo comienzo. — Jean-Paul Sartre",
    "La vida es demasiado corta para ser pequeña. — Benjamin Disraeli",
    "La vida es una aventura atrevida o no es nada. — Helen Keller",
    "La verdadera sabiduría consiste en conocer la propia ignorancia. — Sócrates",
    "El secreto de la existencia humana no es solo vivir, sino tener algo por lo que vivir. — Fiódor Dostoyevski",
    "El hombre no puede descubrir nuevos océanos a menos que tenga el valor de perder de vista la orilla. — André Gide",
    "Antes de juzgar mi vida o mi carácter, ponte en mis zapatos y recorre el camino que yo he recorrido. — Atticus",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre. — Mahatma Gandhi",
    "El hombre que mueve montañas comienza cargando pequeñas piedras. — Proverbio chino",
    "Es durante las tormentas que descubrimos el coraje de los marineros. — Thomas Fuller",
    "Odio cómo la gente romantiza el sufrimiento en lugar de valorar cada momento. — Marina Keegan",
    "No puedes entrar dos veces en el mismo río, porque fluyen aguas siempre nuevas. — Heráclito",
    "Nada es permanente excepto el cambio. — Heráclito",
    "La vida es lo que hacemos de ella. Los viajes son los viajeros. Lo que vemos no es lo que vemos, sino lo que somos. — Fernando Pessoa",
    "No deberíamos tener miedo a la muerte, sino a no haber comenzado a vivir nunca. — Marco Aurelio",
    "El hombre que cree que sabe algo, no sabe nada. El hombre que sabe que no sabe nada, lo sabe todo. — Sócrates",
    "Todo el mundo piensa en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo. — León Tolstói",
    "Somos lo que repetidamente hacemos. La excelencia, por lo tanto, no es un acto, sino un hábito. — Aristóteles",
    "La mente que se abre a una nueva idea nunca vuelve a su tamaño original. — Albert Einstein",
    "Dentro de veinte años estarás más decepcionado por las cosas que no hiciste que por las que hiciste. — Mark Twain",
    "Sé el cambio que quieres ver en el mundo. — Mahatma Gandhi",
    "No importa lo lento que vayas, siempre y cuando no te detengas. — Confucio",
    "Todo lo que somos es el resultado de lo que hemos pensado. — Buda",
    "La única manera de hacer un gran trabajo es amar lo que haces. — Steve Jobs",
    "Lo más difícil no es aceptar que todo termina, sino entender que a veces todo termina antes de comenzar. — José Saramago",
    "Por cada minuto que estás enojado, pierdes sesenta segundos de felicidad. — Ralph Waldo Emerson"
  ],

  // Italian quotes
  it: [
    "La vita è breve, l'arte è lunga. — Ippocrate",
    "Il tempo è la cosa più preziosa che una persona possa spendere. — Teofrasto",
    "Il saggio non si siede a lamentarsi, ma gioisce di aver vissuto. — William Shakespeare",
    "La nostra paura della morte è come la nostra paura dell'oceano: sta nella sua vastità, non nelle sue onde. — Rabindranath Tagore",
    "Il destino mescola le carte, e noi giochiamo. — Arthur Schopenhauer",
    "La vita è come andare in bicicletta. Per mantenere l'equilibrio, devi continuare a muoverti. — Albert Einstein",
    "La vita è breve, ma se sai come usarla, sarà abbastanza lunga. — Seneca",
    "Non è il tempo che cambia le cose, ma ciò che ne facciamo. — Thoreau",
    "Solo una vita vissuta per gli altri vale la pena di essere vissuta. — Albert Einstein",
    "La vita è ciò che accade mentre sei occupato a fare altri progetti. — John Lennon",
    "L'essenza della vita è andare avanti; chi si è fermato, è già morto. — Machado de Assis",
    "La vita è un flusso costante; nulla rimane uguale. — Eraclito",
    "Ogni uomo muore. Non ogni uomo vive veramente. — William Wallace",
    "La vita è come un'eco: se non ti piace quello che vedi, cambia quello che fai. — Jim Rohn",
    "La più grande gloria nel vivere non sta nel non cadere mai, ma nel rialzarsi ogni volta che cadiamo. — Nelson Mandela",
    "Una vita non esaminata non vale la pena di essere vissuta. — Socrate",
    "La vita è come una macchina fotografica: concentrati su ciò che è importante, cattura bei momenti, sviluppa i negativi in positivi. — Sconosciuto",
    "Il tempo è un bambino che gioca a dadi: regno di un bambino. — Eraclito",
    "La vita senza riflessione non vale la pena di essere vissuta. — Socrate",
    "Non contare i giorni, fai che i giorni contino. — Muhammad Ali",
    "La vita è davvero semplice, ma insistiamo nel renderla complicata. — Confucio",
    "La più grande scoperta della mia generazione è che gli esseri umani possono cambiare le loro vite cambiando i loro atteggiamenti mentali. — William James",
    "La felicità non sta nel vivere, ma nel saper vivere. — Fëdor Dostoevskij",
    "La vita è un eterno nuovo inizio. — Jean-Paul Sartre",
    "La vita è troppo breve per essere piccola. — Benjamin Disraeli",
    "La vita è un'avventura audace o non è niente. — Helen Keller",
    "La vera saggezza consiste nel conoscere la propria ignoranza. — Socrate",
    "Il segreto dell'esistenza umana non è solo vivere, ma avere qualcosa per cui vivere. — Fëdor Dostoevskij",
    "L'uomo non può scoprire nuovi oceani finché non ha il coraggio di perdere di vista la riva. — André Gide",
    "Prima di giudicare la mia vita o il mio carattere, metti le mie scarpe e percorri il cammino che ho percorso io. — Atticus",
    "Vivi come se dovessi morire domani. Impara come se dovessi vivere per sempre. — Mahatma Gandhi",
    "L'uomo che sposta le montagne comincia portando via piccole pietre. — Proverbio cinese",
    "È durante le tempeste che scopriamo il coraggio dei marinai. — Thomas Fuller",
    "Odio come le persone romanticizzano la sofferenza invece di valorizzare ogni momento. — Marina Keegan",
    "Non puoi entrare due volte nello stesso fiume, perché scorrono sempre nuove acque. — Eraclito",
    "Niente è permanente tranne il cambiamento. — Eraclito",
    "La vita è ciò che ne facciamo. I viaggi sono i viaggiatori. Ciò che vediamo non è ciò che vediamo, ma ciò che siamo. — Fernando Pessoa",
    "Non dovremmo avere paura della morte, ma di non aver mai iniziato a vivere. — Marco Aurelio",
    "L'uomo che pensa di sapere qualcosa, non sa nulla. L'uomo che sa di non sapere nulla, sa tutto. — Socrate",
    "Tutti pensano a cambiare il mondo, ma nessuno pensa a cambiare se stesso. — Leo Tolstoj",
    "Siamo ciò che facciamo ripetutamente. L'eccellenza, quindi, non è un atto ma un'abitudine. — Aristotele",
    "La mente che si apre a una nuova idea non torna mai alla sua dimensione originale. — Albert Einstein",
    "Tra vent'anni sarai più deluso dalle cose che non hai fatto che da quelle che hai fatto. — Mark Twain",
    "Sii il cambiamento che vuoi vedere nel mondo. — Mahatma Gandhi",
    "Non importa quanto lentamente vai, purché non ti fermi. — Confucio",
    "Tutto ciò che siamo è il risultato di ciò che abbiamo pensato. — Buddha",
    "L'unico modo per fare un ottimo lavoro è amare quello che fai. — Steve Jobs",
    "La cosa più difficile non è accettare che tutto finisce, ma capire che a volte tutto finisce prima ancora di iniziare. — José Saramago",
    "Per ogni minuto in cui sei arrabbiato, perdi sessanta secondi di felicità. — Ralph Waldo Emerson"
  ],

  // German quotes
  de: [
    "Das Leben ist kurz, die Kunst ist lang. — Hippokrates",
    "Zeit ist das Wertvollste, was ein Mensch ausgeben kann. — Theophrastus",
    "Der Weise sitzt nicht um zu klagen, sondern freut sich, gelebt zu haben. — William Shakespeare",
    "Unsere Angst vor dem Tod ist wie unsere Angst vor dem Ozean: Sie liegt in seiner Weite, nicht in seinen Wellen. — Rabindranath Tagore",
    "Das Schicksal mischt die Karten, und wir spielen. — Arthur Schopenhauer",
    "Das Leben ist wie Fahrradfahren. Um das Gleichgewicht zu halten, musst du in Bewegung bleiben. — Albert Einstein",
    "Das Leben ist kurz, aber wenn du weißt, wie man es nutzt, wird es lang genug sein. — Seneca",
    "Es ist nicht die Zeit, die Dinge verändert, sondern was wir daraus machen. — Thoreau",
    "Nur ein Leben, das für andere gelebt wird, ist lebenswert. — Albert Einstein",
    "Leben ist das, was passiert, während du eifrig dabei bist, andere Pläne zu machen. — John Lennon",
    "Das Wesen des Lebens ist, vorwärts zu gehen; wer stehen geblieben ist, ist bereits tot. — Machado de Assis",
    "Das Leben ist ein ständiger Fluss; nichts bleibt gleich. — Heraklit",
    "Jeder Mann stirbt. Nicht jeder Mann lebt wirklich. — William Wallace",
    "Das Leben ist wie ein Echo: Wenn dir nicht gefällt, was du siehst, ändere, was du tust. — Jim Rohn",
    "Die größte Ehre im Leben liegt nicht darin, niemals zu fallen, sondern jedes Mal wieder aufzustehen, wenn wir fallen. — Nelson Mandela",
    "Ein nicht hinterfragtes Leben ist nicht lebenswert. — Sokrates",
    "Das Leben ist wie eine Kamera: Konzentriere dich auf das Wichtige, halte gute Momente fest, entwickle Negative zu Positiven. — Unbekannt",
    "Die Zeit ist ein Kind, das Würfel spielt: das Reich eines Kindes. — Heraklit",
    "Ein Leben ohne Reflexion ist nicht lebenswert. — Sokrates",
    "Zähle nicht die Tage, mache die Tage zählen. — Muhammad Ali",
    "Das Leben ist wirklich einfach, aber wir bestehen darauf, es kompliziert zu machen. — Konfuzius",
    "Die größte Entdeckung meiner Generation ist, dass Menschen ihr Leben verändern können, indem sie ihre Geisteshaltung ändern. — William James",
    "Glück liegt nicht im Leben, sondern im Wissen, wie man lebt. — Fjodor Dostojewski",
    "Das Leben ist ein ewiger Neuanfang. — Jean-Paul Sartre",
    "Das Leben ist zu kurz, um klein zu sein. — Benjamin Disraeli",
    "Das Leben ist entweder ein wagemutiges Abenteuer oder nichts. — Helen Keller",
    "Wahre Weisheit besteht darin, die eigene Unwissenheit zu erkennen. — Sokrates",
    "Das Geheimnis der menschlichen Existenz liegt nicht nur darin zu leben, sondern auch zu wissen, wofür man lebt. — Fjodor Dostojewski",
    "Der Mensch kann keine neuen Ozeane entdecken, wenn er nicht den Mut hat, die Küste aus den Augen zu verlieren. — André Gide",
    "Bevor du mein Leben oder meinen Charakter beurteilst, zieh meine Schuhe an und gehe den Weg, den ich gegangen bin. — Atticus",
    "Lebe, als würdest du morgen sterben. Lerne, als würdest du ewig leben. — Mahatma Gandhi",
    "Der Mann, der Berge versetzt, beginnt damit, kleine Steine wegzutragen. — Chinesisches Sprichwort",
    "Es ist während der Stürme, dass wir den Mut der Seeleute entdecken. — Thomas Fuller",
    "Ich hasse es, wie Menschen das Leiden romantisieren, anstatt jeden Moment zu schätzen. — Marina Keegan",
    "Man kann nicht zweimal in denselben Fluss steigen, denn frisches Wasser fließt stets nach. — Heraklit",
    "Nichts ist beständig außer der Veränderung. — Heraklit",
    "Das Leben ist das, was wir daraus machen. Reisen sind Reisende. Was wir sehen, ist nicht das, was wir sehen, sondern was wir sind. — Fernando Pessoa",
    "Wir sollten keine Angst vor dem Tod haben, sondern davor, nie begonnen zu haben zu leben. — Marcus Aurelius",
    "Der Mann, der glaubt etwas zu wissen, weiß nichts. Der Mann, der weiß, dass er nichts weiß, weiß alles. — Sokrates",
    "Jeder denkt daran, die Welt zu verändern, aber niemand denkt daran, sich selbst zu verändern. — Leo Tolstoi",
    "Wir sind, was wir wiederholt tun. Exzellenz ist daher keine Handlung, sondern eine Gewohnheit. — Aristoteles",
    "Der Geist, der sich einer neuen Idee öffnet, kehrt nie zu seiner ursprünglichen Größe zurück. — Albert Einstein",
    "In zwanzig Jahren wirst du mehr von den Dingen enttäuscht sein, die du nicht getan hast, als von den Dingen, die du getan hast. — Mark Twain",
    "Sei du selbst die Veränderung, die du dir wünschst für diese Welt. — Mahatma Gandhi",
    "Es ist nicht wichtig, wie langsam du gehst, solange du nicht stehen bleibst. — Konfuzius",
    "Alles, was wir sind, ist das Ergebnis dessen, was wir gedacht haben. — Buddha",
    "Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was du tust. — Steve Jobs",
    "Das Schwierigste ist nicht, zu akzeptieren, dass alles endet, sondern zu verstehen, dass manchmal alles endet, bevor es überhaupt begonnen hat. — José Saramago",
    "Für jede Minute, in der du wütend bist, verlierst du sechzig Sekunden Glück. — Ralph Waldo Emerson"
  ],
  
  // French quotes
  fr: [
    "La vie est courte, l'art est long. — Hippocrate",
    "Le temps est la chose la plus précieuse qu'un homme puisse dépenser. — Théophraste",
    "Le sage ne s'assied pas pour se lamenter, mais se réjouit d'avoir vécu. — William Shakespeare",
    "Notre peur de la mort est comme notre peur de l'océan : elle réside dans son immensité, pas dans ses vagues. — Rabindranath Tagore",
    "Le destin mélange les cartes, et nous jouons. — Arthur Schopenhauer",
    "La vie est comme une bicyclette. Pour garder l'équilibre, il faut avancer. — Albert Einstein",
    "La vie est brève, mais si tu sais comment l'utiliser, elle sera assez longue. — Sénèque",
    "Ce n'est pas le temps qui change les choses, mais ce que nous en faisons. — Thoreau",
    "Seule une vie vécue pour les autres vaut la peine d'être vécue. — Albert Einstein",
    "La vie est ce qui arrive pendant que vous êtes occupé à faire d'autres projets. — John Lennon",
    "L'essence de la vie est d'aller de l'avant ; celui qui s'est arrêté est déjà mort. — Machado de Assis",
    "La vie est un flux constant ; rien ne reste pareil. — Héraclite",
    "Tout homme meurt. Tout homme ne vit pas vraiment. — William Wallace",
    "La vie est comme un écho : si vous n'aimez pas ce que vous voyez, changez ce que vous faites. — Jim Rohn",
    "La plus grande gloire dans la vie ne réside pas dans le fait de ne jamais tomber, mais dans celui de se relever à chaque fois que nous tombons. — Nelson Mandela",
    "Une vie non examinée ne vaut pas la peine d'être vécue. — Socrate",
    "La vie est comme un appareil photo : concentrez-vous sur ce qui est important, capturez les bons moments, développez les négatifs en positifs. — Inconnu",
    "Le temps est un enfant qui joue aux dés : royaume d'enfant. — Héraclite",
    "La vie sans réflexion ne vaut pas la peine d'être vécue. — Socrate",
    "Ne comptez pas les jours, faites que les jours comptent. — Muhammad Ali",
    "La vie est vraiment simple, mais nous insistons pour la rendre compliquée. — Confucius",
    "La plus grande découverte de ma génération est que les êtres humains peuvent changer leur vie en changeant leurs attitudes mentales. — William James",
    "Le bonheur n'est pas dans le vivre, mais dans le savoir-vivre. — Fiodor Dostoïevski",
    "La vie est un éternel recommencement. — Jean-Paul Sartre",
    "La vie est trop courte pour être petite. — Benjamin Disraeli",
    "La vie est soit une aventure audacieuse, soit rien du tout. — Helen Keller",
    "La vraie sagesse consiste à connaître sa propre ignorance. — Socrate",
    "Le secret de l'existence humaine ne consiste pas seulement à vivre, mais à savoir pourquoi on vit. — Fiodor Dostoïevski",
    "L'homme ne peut découvrir de nouveaux océans tant qu'il n'a pas le courage de perdre de vue le rivage. — André Gide",
    "Avant de juger ma vie ou mon caractère, mets mes chaussures et parcours le chemin que j'ai parcouru. — Atticus",
    "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre éternellement. — Mahatma Gandhi",
    "L'homme qui déplace des montagnes commence par déplacer de petites pierres. — Proverbe chinois",
    "C'est pendant les tempêtes que nous découvrons le courage des marins. — Thomas Fuller",
    "Je déteste comment les gens romantisent la souffrance au lieu de valoriser chaque moment. — Marina Keegan",
    "On ne peut pas entrer deux fois dans le même fleuve, car de nouvelles eaux coulent toujours. — Héraclite",
    "Rien n'est permanent, sauf le changement. — Héraclite",
    "La vie est ce que nous en faisons. Les voyages sont les voyageurs. Ce que nous voyons n'est pas ce que nous voyons, mais ce que nous sommes. — Fernando Pessoa",
    "Nous ne devrions pas avoir peur de la mort, mais de n'avoir jamais commencé à vivre. — Marc Aurèle",
    "L'homme qui pense savoir quelque chose ne sait rien. L'homme qui sait qu'il ne sait rien, sait tout. — Socrate",
    "Tout le monde pense à changer le monde, mais personne ne pense à se changer soi-même. — Léon Tolstoï",
    "Nous sommes ce que nous faisons répétitivement. L'excellence n'est donc pas un acte, mais une habitude. — Aristote",
    "L'esprit qui s'ouvre à une nouvelle idée ne revient jamais à sa taille d'origine. — Albert Einstein",
    "Dans vingt ans, vous serez plus déçu par les choses que vous n'avez pas faites que par celles que vous avez faites. — Mark Twain",
    "Sois le changement que tu veux voir dans le monde. — Mahatma Gandhi",
    "Peu importe la lenteur à laquelle vous allez, tant que vous n'arrêtez pas. — Confucius",
    "Tout ce que nous sommes est le résultat de ce que nous avons pensé. — Bouddha",
    "La seule façon de faire du bon travail est d'aimer ce que vous faites. — Steve Jobs",
    "Le plus difficile n'est pas d'accepter que tout finisse, mais de comprendre que parfois tout finit avant même d'avoir commencé. — José Saramago",
    "Pour chaque minute où vous êtes en colère, vous perdez soixante secondes de bonheur. — Ralph Waldo Emerson"
  ],
  
  // Russian quotes
  ru: [
    "Жизнь коротка, искусство вечно. — Гиппократ",
    "Время — самая ценная вещь, которую человек может потратить. — Теофраст",
    "Мудрый не сидит и не скорбит, а радуется, что жил. — Уильям Шекспир",
    "Наш страх смерти подобен нашему страху перед океаном: он в его необъятности, а не в его волнах. — Рабиндранат Тагор",
    "Судьба тасует карты, а мы играем. — Артур Шопенгауэр",
    "Жизнь — как езда на велосипеде. Чтобы сохранить равновесие, ты должен двигаться. — Альберт Эйнштейн",
    "Жизнь коротка, но если ты умеешь ею пользоваться, она будет достаточно долгой. — Сенека",
    "Не время меняет вещи, а то, что мы с ним делаем. — Торо",
    "Только жизнь, прожитая для других, стоит того, чтобы жить. — Альберт Эйнштейн",
    "Жизнь — это то, что происходит с тобой, пока ты строишь другие планы. — Джон Леннон",
    "Сущность жизни в том, чтобы идти вперед; кто остановился, тот уже умер. — Мачадо де Ассис",
    "Жизнь — это постоянный поток; ничто не остается прежним. — Гераклит",
    "Каждый человек умирает. Но не каждый по-настоящему живет. — Уильям Уоллес",
    "Жизнь подобна эху: если тебе не нравится то, что ты видишь, измени то, что ты делаешь. — Джим Рон",
    "Величайшая слава в жизни заключается не в том, чтобы никогда не падать, а в том, чтобы подниматься каждый раз, когда мы падаем. — Нельсон Мандела",
    "Непрожитая жизнь не стоит того, чтобы жить. — Сократ",
    "Жизнь подобна фотоаппарату: фокусируйся на важном, запечатлевай хорошие моменты, превращай негативы в позитивы. — Неизвестно",
    "Время — это ребенок, играющий в кости: царство ребенка. — Гераклит",
    "Жизнь без размышлений не стоит того, чтобы жить. — Сократ",
    "Не считай дни, сделай так, чтобы дни считались. — Мухаммед Али",
    "Жизнь на самом деле проста, но мы настаиваем на том, чтобы сделать ее сложной. — Конфуций",
    "Величайшее открытие моего поколения состоит в том, что люди могут изменить свою жизнь, изменив свое отношение к ней. — Уильям Джеймс",
    "Счастье не в том, чтобы жить, а в том, чтобы знать, как жить. — Федор Достоевский",
    "Жизнь — это вечное новое начало. — Жан-Поль Сартр",
    "Жизнь слишком коротка, чтобы быть маленькой. — Бенджамин Дизраэли",
    "Жизнь — это либо дерзкое приключение, либо ничто. — Хелен Келлер",
    "Истинная мудрость заключается в осознании собственного невежества. — Сократ",
    "Тайна человеческого существования не только в том, чтобы жить, но и в том, для чего жить. — Федор Достоевский",
    "Человек не может открыть новые океаны, пока не наберется смелости потерять из виду берег. — Андре Жид",
    "Прежде чем судить о моей жизни или характере, надень мои ботинки и пройди путь, который прошел я. — Аттикус",
    "Живи так, как будто завтра умрешь. Учись так, как будто будешь жить вечно. — Махатма Ганди",
    "Человек, который двигает горы, начинает с переноски мелких камней. — Китайская пословица",
    "Именно во время бурь мы открываем мужество моряков. — Томас Фуллер",
    "Я ненавижу, как люди романтизируют страдания вместо того, чтобы ценить каждый момент. — Марина Киган",
    "Нельзя дважды войти в одну и ту же реку, ибо новые воды постоянно текут. — Гераклит",
    "Ничто не постоянно, кроме перемен. — Гераклит",
    "Жизнь — это то, что мы из нее делаем. Путешествия — это путешественники. То, что мы видим, — это не то, что мы видим, а то, что мы есть. — Фернандо Пессоа",
    "Мы должны бояться не смерти, а того, что никогда не начинали жить. — Марк Аврелий",
    "Человек, который думает, что знает что-то, ничего не знает. Человек, который знает, что ничего не знает, знает все. — Сократ",
    "Все думают о том, как изменить мир, но никто не думает о том, как изменить себя. — Лев Толстой",
    "Мы — то, что мы постоянно делаем. Совершенство, следовательно, не действие, а привычка. — Аристотель",
    "Разум, однажды расширивший свои границы, никогда не вернётся в прежние. — Альберт Эйнштейн",
    "Через двадцать лет вы будете больше разочарованы теми вещами, которые вы не делали, чем теми, которые вы сделали. — Марк Твен",
    "Будь тем изменением, которое ты хочешь видеть в мире. — Махатма Ганди",
    "Неважно, как медленно ты идешь, главное, что ты не останавливаешься. — Конфуций",
    "Все, что мы есть, — результат наших мыслей. — Будда",
    "Единственный способ сделать отличную работу — любить то, что ты делаешь. — Стив Джобс",
    "Самое трудное — не принять, что все заканчивается, а понять, что иногда все заканчивается до того, как началось. — Жозе Сарамаго",
    "За каждую минуту гнева вы теряете шестьдесят секунд счастья. — Ральф Уолдо Эмерсон"
  ],
  
  // Chinese quotes
  zh: [
    "生命短暂，艺术长存。 — 希波克拉底",
    "时间是人能花费的最宝贵的东西。 — 泰奥弗拉斯托斯",
    "智者不会坐下来哀叹，而是因为活过而欣喜。 — 威廉·莎士比亚",
    "我们对死亡的恐惧就像对大海的恐惧：它在于它的浩瀚，而非它的波涛。 — 泰戈尔",
    "命运洗牌，我们则打牌。 — 亚瑟·叔本华",
    "生活就像骑自行车，要保持平衡就得不断前进。 — 阿尔伯特·爱因斯坦",
    "生命虽短暂，但如果你懂得如何使用它，它就会足够长。 — 塞内加",
    "不是时间改变了事物，而是我们如何使用它。 — 梭罗",
    "只有为他人而活的生命才值得活。 — 阿尔伯特·爱因斯坦",
    "生活就是当你忙着制定其他计划时发生的事情。 — 约翰·列侬",
    "生命的本质是向前走；停滞不前的人已经死亡。 — 马查多·德·阿西斯",
    "生命是一个不断流动的过程；没有什么保持不变。 — 赫拉克利特",
    "每个人都会死。不是每个人都真正活过。 — 威廉·华莱士",
    "生活就像回声：如果你不喜欢所见，就改变你所为。 — 吉姆·罗恩",
    "生命中最大的荣耀不在于永不跌倒，而在于每次跌倒后都能爬起来。 — 纳尔逊·曼德拉",
    "未经审视的生活不值得过。 — 苏格拉底",
    "生活就像相机：聚焦于重要的事，捕捉美好时刻，把负片冲洗成正片。 — 未知",
    "时间是个玩骰子的孩子：孩子的王国。 — 赫拉克利特",
    "没有反思的生活不值得过。 — 苏格拉底",
    "不要数日子，要让日子有价值。 — 穆罕默德·阿里",
    "生活本来很简单，但我们坚持要把它变复杂。 — 孔子",
    "我这一代最伟大的发现是，人类可以通过改变心态来改变生活。 — 威廉·詹姆斯",
    "幸福不在于生活，而在于知道如何生活。 — 陀思妥耶夫斯基",
    "生活是永恒的新开始。 — 让-保罗·萨特",
    "生命太短暂，不该渺小度过。 — 本杰明·迪斯雷利",
    "生活要么是一次大胆的冒险，要么什么都不是。 — 海伦·凯勒",
    "真正的智慧在于认识自己的无知。 — 苏格拉底",
    "人类存在的秘密不仅在于生活，还在于知道为何而生活。 — 陀思妥耶夫斯基",
    "人不能发现新大陆，除非他有勇气离开熟悉的海岸线。 — 安德烈·纪德",
    "在评判我的生活或性格之前，穿上我的鞋子走一走我走过的路。 — 阿提克斯",
    "活着如同明天将死，学习如同永远活着。 — 圣雄甘地",
    "移山的人是从搬运小石头开始的。 — 中国谚语",
    "正是在风暴中我们发现了水手的勇气。 — 托马斯·富勒",
    "我讨厌人们把苦难浪漫化，而不是珍惜每一刻。 — 玛丽娜·基根",
    "人不能两次踏入同一条河流，因为新的水总是流动的。 — 赫拉克利特",
    "唯一不变的是变化本身。 — 赫拉克利特",
    "生活就是我们创造的。旅行就是旅行者自己。我们所见不是我们所见，而是我们自己。 — 费尔南多·佩索阿",
    "我们不应该害怕死亡，而应该害怕从未开始生活。 — 马可·奥勒留",
    "以为自己知道一些事的人，什么都不知道。知道自己一无所知的人，知道一切。 — 苏格拉底",
    "每个人都想改变世界，却没有人想改变自己。 — 列夫·托尔斯泰",
    "我们是我们重复做的事。因此，卓越不是一种行为，而是一种习惯。 — 亚里士多德",
    "一旦开启的心智永远不会回到原来的大小。 — 阿尔伯特·爱因斯坦",
    "二十年后，你会为没做过的事感到失望，而不是为做过的事。 — 马克·吐温",
    "成为你想在世界上看到的改变。 — 圣雄甘地",
    "不管你走得多慢，只要你不停下来。 — 孔子",
    "我们所是的一切，都是我们思想的结果。 — 佛陀",
    "做出伟大工作的唯一方法是热爱你所做的事。 — 史蒂夫·乔布斯",
    "最难的不是接受一切都会结束，而是理解有时一切在开始之前就结束了。 — 若泽·萨拉马戈",
    "每当你生气的每一分钟，你就失去六十秒的幸福。 — 拉尔夫·沃尔多·爱默生"
  ],
  
  // Japanese quotes
  ja: [
    "人生は短く、芸術は長い。 — ヒポクラテス",
    "時間は人が費やすことができる最も貴重なものである。 — テオフラストス",
    "賢者は座って嘆くのではなく、生きたことを喜ぶ。 — ウィリアム・シェイクスピア",
    "死への恐怖は海への恐怖のようなもの：それはその広大さにあり、波にあるのではない。 — ラビンドラナート・タゴール",
    "運命はカードをシャッフルし、私たちはプレイする。 — アーサー・ショーペンハウアー",
    "人生は自転車に乗るようなもの。バランスを保つには、動き続けなければならない。 — アルベルト・アインシュタイン",
    "人生は短いが、使い方を知っていれば十分に長い。 — セネカ",
    "時間が物事を変えるのではなく、私たちがそれをどう使うかだ。 — ソロー",
    "他者のために生きる人生だけが、生きる価値がある。 — アルベルト・アインシュタイン",
    "人生とは、あなたが他の計画を立てている間に起こることである。 — ジョン・レノン",
    "人生の本質は前進すること。立ち止まった者は既に死んでいる。 — マシャード・デ・アシス",
    "人生は絶え間ない流れ。何も同じままではない。 — ヘラクレイトス",
    "すべての人は死ぬ。すべての人が本当に生きるわけではない。 — ウィリアム・ウォレス",
    "人生はエコーのようなもの：見たものが気に入らないなら、やっていることを変えよう。 — ジム・ローン",
    "人生における最大の栄光は、決して倒れないことではなく、倒れるたびに立ち上がることにある。 — ネルソン・マンデラ",
    "検証されない人生は生きる価値がない。 — ソクラテス",
    "人生はカメラのようなもの：重要なことに焦点を当て、良い瞬間を捉え、ネガティブをポジティブに変える。 — 不明",
    "時間は賽を投げる子供：子供の王国。 — ヘラクレイトス",
    "反省のない人生は生きる価値がない。 — ソクラテス",
    "日々を数えるな、日々に意味を持たせよ。 — モハメド・アリ",
    "人生は本当にシンプルだが、私たちはそれを複雑にすることに固執する。 — 孔子",
    "私の世代の最大の発見は、人間が心の態度を変えることで人生を変えられるということだ。 — ウィリアム・ジェームズ",
    "幸福は生きることにあるのではなく、どう生きるかを知ることにある。 — フョードル・ドストエフスキー",
    "人生は永遠の新たな始まりである。 — ジャン＝ポール・サルトル",
    "人生は小さくあるには短すぎる。 — ベンジャミン・ディズレーリ",
    "人生は大胆な冒険か、さもなくば無である。 — ヘレン・ケラー",
    "真の知恵は自らの無知を知ることにある。 — ソクラテス",
    "人間存在の秘密は、単に生きるだけでなく、何のために生きるかを知ることにもある。 — フョードル・ドストエフスキー",
    "人は岸を見失う勇気がなければ、新しい海を発見することはできない。 — アンドレ・ジッド",
    "私の人生や性格を判断する前に、私の靴を履いて私が歩んだ道を歩んでみてください。 — アティカス",
    "明日死ぬかのように生き、永遠に生きるかのように学べ。 — マハトマ・ガンジー",
    "山を動かす人は、小さな石を運ぶことから始める。 — 中国のことわざ",
    "嵐の中で私たちは船乗りの勇気を発見する。 — トーマス・フラー",
    "人々が苦しみを美化して、一瞬一瞬を大切にしないことが嫌いだ。 — マリーナ・キーガン",
    "同じ川に二度入ることはできない、常に新しい水が流れているから。 — ヘラクレイトス",
    "変化以外に永続的なものはない。 — ヘラクレイトス",
    "人生とは私たちがそれを作るもの。旅は旅人。私たちが見るものは私たちが見るものではなく、私たちが何者であるかだ。 — フェルナンド・ペソア",
    "私たちが恐れるべきは死ではなく、生き始めなかったことだ。 — マルクス・アウレリウス",
    "何かを知っていると思う人は何も知らない。自分が何も知らないことを知っている人は全てを知っている。 — ソクラテス",
    "誰もが世界を変えることを考えるが、誰も自分自身を変えることを考えない。 — レフ・トルストイ",
    "私たちは繰り返し行うことである。したがって、優秀さは行為ではなく習慣である。 — アリストテレス",
    "新しいアイデアに開かれた心は、二度と元の大きさには戻らない。 — アルベルト・アインシュタイン",
    "二十年後、あなたはやらなかったことにより、やったことよりも失望するだろう。 — マーク・トウェイン",
    "世界に見たい変化を、自分自身になりなさい。 — マハトマ・ガンジー",
    "どれだけゆっくり進んでも、止まらなければ大丈夫。 — 孔子",
    "私たちの全ては、私たちが考えたことの結果である。 — ブッダ",
    "素晴らしい仕事をする唯一の方法は、自分のやっていることを愛することだ。 — スティーブ・ジョブズ",
    "最も難しいのは、すべてが終わることを受け入れることではなく、時にはすべてが始まる前に終わることを理解することだ。 — ジョゼ・サラマーゴ",
    "怒りに費やす1分ごとに、幸せの60秒を失う。 — ラルフ・ワルド・エマーソン"
  ],
  
  // Indonesian quotes
  id: [
    "Hidup itu singkat, seni itu panjang. — Hippocrates",
    "Waktu adalah hal paling berharga yang bisa dihabiskan seseorang. — Theophrastus",
    "Orang bijak tidak duduk untuk meratap, tetapi bersukacita karena telah hidup. — William Shakespeare",
    "Ketakutan kita akan kematian seperti ketakutan kita akan lautan: itu ada dalam keluasannya, bukan dalam ombaknya. — Rabindranath Tagore",
    "Takdir mengocok kartu, dan kita memainkannya. — Arthur Schopenhauer",
    "Hidup itu seperti naik sepeda. Untuk menjaga keseimbangan, kamu harus terus bergerak. — Albert Einstein",
    "Hidup itu singkat, tetapi jika kamu tahu cara menggunakannya, itu akan cukup panjang. — Seneca",
    "Bukan waktu yang mengubah hal-hal, tetapi apa yang kita lakukan dengannya. — Thoreau",
    "Hanya kehidupan yang dijalani untuk orang lain yang layak dijalani. — Albert Einstein",
    "Hidup adalah apa yang terjadi saat kamu sibuk membuat rencana lain. — John Lennon",
    "Esensi kehidupan adalah untuk terus maju; siapa yang berhenti, sudah mati. — Machado de Assis",
    "Hidup adalah aliran yang konstan; tidak ada yang tetap sama. — Heraclitus",
    "Setiap orang mati. Tidak semua orang benar-benar hidup. — William Wallace",
    "Hidup itu seperti gema: jika kamu tidak suka apa yang kamu lihat, ubahlah apa yang kamu lakukan. — Jim Rohn",
    "Kemuliaan terbesar dalam hidup bukanlah tidak pernah jatuh, tetapi bangkit setiap kali kita jatuh. — Nelson Mandela",
    "Hidup yang tidak direnungkan tidak layak dijalani. — Socrates",
    "Hidup itu seperti kamera: fokus pada yang penting, tangkap momen baik, kembangkan negatif menjadi positif. — Tidak diketahui",
    "Waktu adalah anak yang bermain dadu: kerajaan anak-anak. — Heraclitus",
    "Hidup tanpa refleksi tidak layak dijalani. — Socrates",
    "Jangan menghitung hari-hari, buatlah hari-hari itu berarti. — Muhammad Ali",
    "Hidup itu sebenarnya sederhana, tapi kita bersikeras membuatnya rumit. — Confucius",
    "Penemuan terbesar generasi saya adalah bahwa manusia dapat mengubah hidup mereka dengan mengubah sikap mental mereka. — William James",
    "Kebahagiaan bukanlah dalam hidup, tetapi dalam mengetahui cara hidup. — Fyodor Dostoevsky",
    "Hidup adalah permulaan baru yang abadi. — Jean-Paul Sartre",
    "Hidup terlalu singkat untuk menjadi kecil. — Benjamin Disraeli",
    "Hidup adalah petualangan yang berani atau bukan apa-apa. — Helen Keller",
    "Kebijaksanaan sejati terletak pada mengetahui ketidaktahuan diri sendiri. — Socrates",
    "Rahasia keberadaan manusia bukan hanya untuk hidup, tetapi juga untuk memiliki sesuatu untuk hidup. — Fyodor Dostoevsky",
    "Manusia tidak dapat menemukan samudra baru kecuali dia memiliki keberanian untuk kehilangan pandangan terhadap pantai. — André Gide",
    "Sebelum menghakimi hidup atau karakterku, pakailah sepatuku dan jalani perjalanan yang telah kujalani. — Atticus",
    "Hiduplah seolah-olah kamu akan mati besok. Belajarlah seolah-olah kamu akan hidup selamanya. — Mahatma Gandhi",
    "Orang yang memindahkan gunung mulai dengan membawa batu-batu kecil. — Pepatah Cina",
    "Dalam badailah kita menemukan keberanian para pelaut. — Thomas Fuller",
    "Aku benci bagaimana orang meromantisasi penderitaan alih-alih menghargai setiap momen. — Marina Keegan",
    "Kamu tidak bisa masuk ke sungai yang sama dua kali, karena air segar selalu mengalir. — Heraclitus",
    "Tidak ada yang permanen kecuali perubahan. — Heraclitus",
    "Hidup adalah apa yang kita buat darinya. Perjalanan adalah para penjelajah. Apa yang kita lihat bukanlah apa yang kita lihat, tetapi apa yang kita adalah. — Fernando Pessoa",
    "Kita seharusnya tidak takut akan kematian, tetapi takut tidak pernah mulai hidup. — Marcus Aurelius",
    "Orang yang berpikir dia tahu sesuatu, tidak tahu apa-apa. Orang yang tahu bahwa dia tidak tahu apa-apa, tahu segalanya. — Socrates",
    "Semua orang berpikir untuk mengubah dunia, tapi tidak ada yang berpikir untuk mengubah dirinya sendiri. — Leo Tolstoy",
    "Kita adalah apa yang kita lakukan berulang kali. Keunggulan, karena itu, bukanlah tindakan tetapi kebiasaan. — Aristoteles",
    "Pikiran yang terbuka terhadap ide baru tidak akan pernah kembali ke ukuran aslinya. — Albert Einstein",
    "Dua puluh tahun dari sekarang kamu akan lebih kecewa oleh hal-hal yang tidak kamu lakukan daripada oleh hal-hal yang kamu lakukan. — Mark Twain",
    "Jadilah perubahan yang ingin kamu lihat di dunia. — Mahatma Gandhi",
    "Tidak masalah seberapa lambat kamu berjalan selama kamu tidak berhenti. — Confucius",
    "Semua yang kita adalah adalah hasil dari apa yang telah kita pikirkan. — Buddha",
    "Satu-satunya cara untuk melakukan pekerjaan hebat adalah mencintai apa yang kamu lakukan. — Steve Jobs",
    "Hal tersulit bukanlah menerima bahwa semuanya berakhir, tetapi memahami bahwa terkadang semuanya berakhir bahkan sebelum dimulai. — José Saramago",
    "Untuk setiap menit kamu marah, kamu kehilangan enam puluh detik kebahagiaan. — Ralph Waldo Emerson"
  ]
};

/**
 * Returns a random quote in the specified language
 * If no language is provided, uses English
 */
export const getRandomQuote = (language: Language = 'en'): string => {
  const quotesInLanguage = lifeQuotes[language] || lifeQuotes.en;
  const randomIndex = Math.floor(Math.random() * quotesInLanguage.length);
  return quotesInLanguage[randomIndex];
};

